#!/usr/bin/env bash
set -euo pipefail
TARGET="$1"
PREFIX="${2:-}" 
POSTFIX="${3:-}" 

read -p 'Enter the value for the secret above: ' SECRET
if [ -z "$SECRET" ]
then
    echo "No secret passed, aborting!"; exit 1
else
    echo $PREFIX$SECRET$POSTFIX > $TARGET
fi
